name: Performance Benchmarks

on:
  push:
    branches:
      - main  # or your main branch
  pull_request:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'  # or your desired Python version
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # or any other dependencies
          pip install pytest
          pip install pytest-benchmark
          pip install hypothesis  # Add this line to install hypothesis
      - name: Run Benchmarks
        run: pytest --benchmark-disable-gc --benchmark-json=benchmark.json test_timebased_logger.py
      - name: Update README with benchmarks
        run: python extract_metrics.py benchmark.json README.md
      - name: Commit updated README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: README.md
          commit_message: "Automated: Update benchmarks in README [skip ci]"