name: Build and Publish Docs

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pdoc3
        run: pip install pdoc3
      - name: Generate HTML docs
        run: pdoc --html timebased_logger.py --output-dir docs
      - name: Rename main HTML file to index.html
        run: mv docs/timebased_logger.html docs/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs